# Image Padding in CNN

## 🎯 Objective

Understand how padding works in Convolutional Neural Networks (CNNs).

---

## 📚 Theory

Padding is the process of adding extra rows and columns around an image before applying convolution.

Padding helps:

- Preserve image dimensions
- Prevent information loss at borders
- Allow filters to process edge pixels

---

## 📌 Types of Padding

- Valid Padding (No Padding)
- Same Padding (Zero Padding)

---

## 📦 Import Libraries

- NumPy

---

## 💻 Implementation

Create a small image matrix and apply zero padding using NumPy.

---

## 📊 Expected Output

- Original Image
- Padded Image

---

## 📖 Conclusion

Padding increases image size by adding extra border pixels before convolution.

---

## 🔑 Key Takeaways

- Padding prevents feature loss.
- Same padding preserves image dimensions.
- Implemented using `numpy.pad()`.

In [1]:
import numpy as np
image = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print("Original Image")
print(image)
padded=np.pad(image,pad_width=1,mode='constant')
print("\nPadded Image:")
print(padded)

Original Image
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Padded Image:
[[0 0 0 0 0]
 [0 1 2 3 0]
 [0 4 5 6 0]
 [0 7 8 9 0]
 [0 0 0 0 0]]
