# Edge Detection using Convolution Kernel

## 🎯 Objective

Perform edge detection using a manually defined convolution kernel.

---

## 📚 Theory

Edge detection highlights boundaries in an image by applying a convolution filter.

A kernel slides over the image and calculates weighted sums.

---

## 📌 Kernel Used

Vertical Edge Detection Kernel

---

## 📦 Import Libraries

- NumPy

---

## 💻 Implementation

Apply the convolution kernel manually.

---

## 📊 Expected Output

- Image Matrix
- Kernel
- Edge Detection Value

---

## 📖 Conclusion

Convolution kernels extract important image features such as edges.

---

## 🔑 Key Takeaways

- Filters detect patterns.
- Convolution extracts image features.

In [1]:
import numpy as np
image =np.array([
    [10,10,10],
    [10,10,10],
    [0,0,0]
])
kernel=np.array([
    [-1,-1,-1],
    [0,0,0],
    [1,1,-1]
])
result=np.sum(image*kernel)
print("image")
print(image)
print("\nkernel:")
print(kernel)
print("\nEdge detection value:")
print(result)

image
[[10 10 10]
 [10 10 10]
 [ 0  0  0]]

kernel:
[[-1 -1 -1]
 [ 0  0  0]
 [ 1  1 -1]]

Edge detection value:
-30
