# Convolution using TensorFlow

## 🎯 Objective

Apply a custom convolution kernel using TensorFlow.

---

## 📚 Theory

TensorFlow allows us to manually define convolution kernels and observe their effect on an image.

---

## 📦 Import Libraries

- TensorFlow
- NumPy

---

## 💻 Implementation

Create an image, define a kernel, and perform convolution.

---

## 📊 Expected Output

- Input Image
- Kernel
- Output Feature Map

---

## 📖 Conclusion

TensorFlow Conv2D performs convolution exactly like manual calculations but much more efficiently.

---

## 🔑 Key Takeaways

- Conv2D performs convolution automatically.
- Custom kernels can be assigned manually.

In [1]:
import tensorflow as tf
import numpy as np

# Input image
image = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
], dtype=np.float32)

image = image.reshape(1, 3, 3, 1)

# CNN layer
conv = tf.keras.layers.Conv2D(
    filters=1,
    kernel_size=(3,3),
    padding='same',
    use_bias=False
)

# Build layer
conv.build((1,3,3,1))

# Set kernel manually
kernel = np.array([
    [-1,-1,-1],
    [ 0, 0, 0],
    [ 1, 1, 1]
], dtype=np.float32)

kernel = kernel.reshape(3,3,1,1)
conv.set_weights([kernel])

# Apply convolution
output = conv(image)

print("Input Image:")
print(image.reshape(3,3))

print("\nKernel:")
print(kernel.reshape(3,3))

print("\nOutput:")
print(output.numpy().reshape(3,3))


Input Image:
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]

Kernel:
[[-1. -1. -1.]
 [ 0.  0.  0.]
 [ 1.  1.  1.]]

Output:
[[  9.  15.  11.]
 [ 12.  18.  12.]
 [ -9. -15. -11.]]
