# Stride Operation (Manual)

## 🎯 Objective

Understand how stride changes the output size during convolution.

---

## 📚 Theory

Stride determines how many pixels the filter moves after each convolution.

Higher stride reduces output dimensions.

---

## 📦 Import Libraries

- NumPy

---

## 💻 Implementation

Implement convolution using stride = 2.

---

## 📊 Expected Output

Input Matrix

Kernel

Output Matrix

---

## 📖 Conclusion

Increasing stride decreases computation and reduces feature map size.

---

## 🔑 Key Takeaways

- Larger stride → Smaller output.
- Faster computation.

In [1]:
import numpy as np

image = np.array([
    [1,2,3,4],
    [5,6,7,8],
    [9,1,2,3],
    [4,5,6,7]
])

kernel = np.array([
    [1,0],
    [0,1]
])

stride = 2

output = np.zeros((2,2), dtype=int)

for i in range(2):
    for j in range(2):
        block = image[i*stride:i*stride+2, j*stride:j*stride+2]
        output[i, j] = np.sum(block * kernel)

print("Input Image:")
print(image)

print("\nKernel:")
print(kernel)

print("\nOutput:")
print(output)

Input Image:
[[1 2 3 4]
 [5 6 7 8]
 [9 1 2 3]
 [4 5 6 7]]

Kernel:
[[1 0]
 [0 1]]

Output:
[[ 7 11]
 [14  9]]
