# Convolution Output using TensorFlow

## 🎯 Objective

Observe the output produced by a convolution layer.

---

## 📚 Theory

A convolution layer generates feature maps by sliding a kernel over an image.

---

## 📦 Import Libraries

- TensorFlow
- NumPy

---

## 💻 Implementation

Apply convolution to a sample image.

---

## 📊 Expected Output

Input Image

Kernel

Output Feature Map

---

## 📖 Conclusion

The output feature map contains extracted image features.

---

## 🔑 Key Takeaways

- Feature maps represent learned patterns.

In [1]:
import tensorflow as tf
import numpy as np

image = np.array([
    [1, 2, 3, 4],
    [5, 6, 7, 8],
    [9, 1, 2, 3],
    [4, 5, 6, 7]
], dtype=np.float32)

image = image.reshape(1, 4, 4, 1)

conv = tf.keras.layers.Conv2D(
    filters=1,
    kernel_size=(2,2),
    strides=1,
    padding='valid',
    use_bias=False
)

conv.build((1,4,4,1))
kernel = np.array([
    [1, 0],
    [0, 1]
], dtype=np.float32)

kernel = kernel.reshape(2,2,1,1)
conv.set_weights([kernel])
output = conv(image)

print("Input Image:")
print(image.reshape(4,4))

print("\nKernel:")
print(kernel.reshape(2,2))

print("\nOutput:")
print(output.numpy().reshape(3,3))

Input Image:
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]
 [9. 1. 2. 3.]
 [4. 5. 6. 7.]]

Kernel:
[[1. 0.]
 [0. 1.]]

Output:
[[ 7.  9. 11.]
 [ 6.  8. 10.]
 [14.  7.  9.]]
